//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_ASPNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public string cedula { get; set; }
        public string nombre { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public string correo { get; set; }
        public string direccion { get; set; }
        public string id { get; set; }
    
        public virtual CUENTA CUENTA { get; set; }
        public virtual TELEFONO TELEFONO { get; set; }
    }
}
